version: "3.2"

services:
  web:
    image: httpd
    ports:
      - 80:80
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs

  db:
    image: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    volumes:
      - /sessions